=== physicsscholars/advanced-beam-line-electronics/configs/ABLE1.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="experiment">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="operator" type="xs:string" minOccurs="1" maxOccurs="1" use="required"/>
				<xs:element name="project" type="xs:string" minOccurs="1" maxOccurs="1" use="required"/>
				<xs:element name="targetDose" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required"/>
				<xs:element name="sample" use="required">
					<xs:complexType>
						<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" use="required"/>
						<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" use="required"/>
						<xs:element name="molarMass" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required">
							<xs:complexType>
								<xs:attribute name="units" type="xs:string" fixed="g/mol"/> 
							</xs:complexType>
						</xs:element>
						<xs:element name="density" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required">
							<xs:complexType>
								<xs:attribute name="units" type="xs:string" fixed="g/cm^3"/> 
							</xs:complexType>
						</xs:element>
						<xs:element name="irradiationArea" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required">
							<xs:complexType>
								<xs:attribute name="units" type="xs:string" fixed="cm^2"/> 
							</xs:complexType>
						</xs:element>
						<xs:element name="srimDamagePeak" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required">
							<xs:complexType>
								<xs:attribute name="units" type="xs:string" fixed="disp*ions/cm"/> 
							</xs:complexType>
						</xs:element>
					</xs:complexType>
				</xs:element>
				<xs:element name="beamLine" use="required">
					<xs:complexType>
						<xs:element name="type" type="xs:string" minOccurs="1" maxOccurs="1" use="required"/>
						<xs:element name="ion" type="xs:string" minOccurs="1" maxOccurs="1" use="required"/>
						<xs:element name="chargeState" type="xs:integer" minOccurs="1" maxOccurs="1" use="required" default="1"/>
						<xs:element name="totalSourceIonEnergy" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required">
							<xs:complexType>
								<xs:attribute name="units" type="xs:string" fixed="kV"/> 
							</xs:complexType>
						</xs:element>
					</xs:complexType>
				</xs:element>
				<xs:element name="runs" use="required">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="run" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="timing" use="required">
											<xs:complexType>
													<xs:sequence>
														<xs:element name="start" type="xs:string" minOccurs="1" maxOccurs="1" use="required"/>
														<xs:element name="stop" type="xs:string" minOccurs="1" maxOccurs="1" use="required"/>
													</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="dose" use="required">
											<xs:complexType>
													<xs:sequence>
														<xs:element name="start" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required"/>
														<xs:element name="stop" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required"/>
													</xs:sequence>
													<xs:attribute name="units" type="xs:string" fixed="dpa"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="fluence" use="required">
											<xs:complexType>
													<xs:sequence>
														<xs:element name="start" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required"/>
														<xs:element name="stop" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required"/>
													</xs:sequence>
													<xs:attribute name="units" type="xs:string" fixed="ions/cm^2""/> 
											</xs:complexType>
										</xs:element>
										<xs:element name="totalCharge" use="required">
											<xs:complexType>
													<xs:sequence>
														<xs:element name="start" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required"/>
														<xs:element name="stop" type="xs:decimal" minOccurs="1" maxOccurs="1" use="required"/>
													</xs:sequence>
													<xs:attribute name="units" type="xs:string" fixed="C"/> 
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== physicsscholars/advanced-beam-line-electronics/trunk/configs/Example_Experiment2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<experiment xmlns="http://engr.wisc.edu/ABLE/Version/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ABLE1.xsd">

  <operator>Example 2 User</operator>

  <project>An example experiment for a longer, more realistic run with an initial run.</project>

  <targetDose>1.500E-5</targetDose>

  <sample>
    <name>Example 2</name>
    <description>Description</description>
    <molarMass units="g/mol">58.000</molarMass>
    <density units="g/cm^3">8.016</density>
    <irradiationArea units="cm^2">1.4559</irradiationArea>
    <srimDamagePeak units="disp*ions/cm">7.470E-5</srimDamagePeak>
  </sample>

  <beamLine>
    <type>Radiation Damage</type>
    <ion>H</ion>
    <chargeState>1</chargeState>
    <totalSourceIonEnergy units="kV">15.0</totalSourceIonEnergy>
  </beamLine>

  <runs>
    <run>
      <timing>
        <start>12/31/2012 14:44:01</start>
        <stop>12/31/2012 14:44:08</stop>
      </timing>
      <dose units="dpa">
        <start>0.000E+0</start>
        <stop>1.118E-12</stop>
      </dose>
      <fluence units="ions/cm^2">
        <start>0.000E+0</start>
        <stop>1.245E+15</stop>
      </fluence>
      <totalCharge units="A">
        <start>0.000E+0</start>
        <stop>2.904E-4</stop>
      </totalCharge>
    </run>
  </runs>

</experiment>

=== physicsscholars/advanced-beam-line-electronics/trunk/configs/Example_Experiment.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<experiment xmlns="http://engr.wisc.edu/ABLE/Version/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ABLE1.xsd">

  <!-- The name of the operator or owner of this sample and experiment -->
  <operator>Example 1 User</operator>

  <!-- A description of the overall project or experiment -->
  <project>An example for a simple approximate 3 minute experiment.</project>

  <!-- The target, or desired dose in DPA for the sample. This value is used -->
  <!-- to determine if the experiment is done. -->
  <targetDose>1.500E-11</targetDose>

  <!-- Information about the sample. All values are required. -->
  <sample>
    <name>Example 1</name>
    <description>Description</description>
    <molarMass units="g/mol">58.000</molarMass>
    <density units="g/cm^3">8.016</density>
    <irradiationArea units="cm^2">1.4559</irradiationArea>
    <srimDamagePeak units="disp*ions/cm">7.470E-5</srimDamagePeak>
  </sample>

  <!-- Information about the beam line. All values are required. -->
  <beamLine>
    <type>Radiation Damage</type>
    <ion>H</ion>
    <chargeState>1</chargeState>
    <totalSourceIonEnergy units="kV">15.0</totalSourceIonEnergy>
  </beamLine>

  <!-- A list of runs, or exposures, for the sample, which are listed in oldest first, most -->
  <!-- recent last. -->
  <runs/>

</experiment>
